DB_DSN=postgres://myuser:mypass@localhost:5432/mydb?sslmode=disable

up: 
	docker-compose up -d

run:
	DSN=$(DB_DSN) go run cmd/gophermart/main.go

down: 
	docker-compose down

run-app: up run

migrate-up:
	migrate -path migrations -database "$(DB_DSN)" up

# Команда для отката
migrate-down:
	migrate -path migrations -database "$(DB_DSN)" down

clean: 
	docker-compose down -v