RUN_ADDRESS=localhost:8081

ACCRUAL_PORT=localhost:8080

ACCRUAL_SYSTEM_ADDRESS=http://$(ACCRUAL_PORT)

DATABASE_URI=postgres://myuser:mypass@localhost:5432/mydb?sslmode=disable
ACCRUAL_BIN=./cmd/accrual/accrual_darwin_arm64

run-accrual:
	chmod +x $(ACCRUAL_BIN)
	$(ACCRUAL_BIN) -a $(ACCRUAL_PORT)

run:
	RUN_ADDRESS=$(RUN_ADDRESS) \
	DATABASE_URI=$(DATABASE_URI) \
	ACCRUAL_SYSTEM_ADDRESS=$(ACCRUAL_SYSTEM_ADDRESS) \
	go run cmd/gophermart/main.go

up: 
	docker-compose up -d

down: 
	docker-compose down

run-app: up run

migrate-up:
	migrate -path migrations -database "$(DATABASE_URI)" up

migrate-down:
	migrate -path migrations -database "$(DATABASE_URI)" down

clean: 
	docker-compose down -v
